<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="73355" started-at="2019-02-08T10:54:05Z" finished-at="2019-02-08T10:55:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="73355" started-at="2019-02-08T10:54:05Z" finished-at="2019-02-08T10:55:18Z">
      <class name="com.elearning.functional.TC69AddUserNegativeTest">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="setUpBeforeClass" is-config="true" duration-ms="20" started-at="2019-02-08T10:54:05Z" finished-at="2019-02-08T10:54:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="setUp" duration-ms="10817" started-at="2019-02-08T10:54:05Z" finished-at="2019-02-08T10:54:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="loginTest" duration-ms="5260" started-at="2019-02-08T10:54:16Z" finished-at="2019-02-08T10:54:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="addNewUserTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="addNewUserTest" duration-ms="15317" started-at="2019-02-08T10:54:22Z" data-provider="excel-inputs" finished-at="2019-02-08T10:54:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12334.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mehadi]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[manzoor@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9876543210]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[manzoor888]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[manzoor]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The user has been added: 12334.0 mehadi] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The user has been added: 12334.0 mehadi] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.elearning.functional.TC69AddUserNegativeTest.addNewUserTest(TC69AddUserNegativeTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewUserTest -->
        <test-method status="FAIL" signature="addNewUserTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="addNewUserTest" duration-ms="11173" started-at="2019-02-08T10:54:37Z" data-provider="excel-inputs" finished-at="2019-02-08T10:54:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alex]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hales]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[alex]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9876543211]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[alex888]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[alex]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The user has been added: alex hales] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The user has been added: alex hales] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.elearning.functional.TC69AddUserNegativeTest.addNewUserTest(TC69AddUserNegativeTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewUserTest -->
        <test-method status="FAIL" signature="addNewUserTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="addNewUserTest" duration-ms="15980" started-at="2019-02-08T10:54:48Z" data-provider="excel-inputs" finished-at="2019-02-08T10:55:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[george]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bush]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[george@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[georgebush]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[george888]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[george]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The user has been added: george bush] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The user has been added: george bush] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.elearning.functional.TC69AddUserNegativeTest.addNewUserTest(TC69AddUserNegativeTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewUserTest -->
        <test-method status="FAIL" signature="addNewUserTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="addNewUserTest" duration-ms="11622" started-at="2019-02-08T10:55:04Z" data-provider="excel-inputs" finished-at="2019-02-08T10:55:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mark]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[angel]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mark@gmail]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9876543213]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[mark888]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[mark]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The user has been added: mark angel] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The user has been added: mark angel] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.elearning.functional.TC69AddUserNegativeTest.addNewUserTest(TC69AddUserNegativeTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewUserTest -->
        <test-method status="PASS" signature="AssertnewUsercreationTest()[pri:3, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="AssertnewUsercreationTest" duration-ms="2" started-at="2019-02-08T10:55:16Z" finished-at="2019-02-08T10:55:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AssertnewUsercreationTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.elearning.functional.TC69AddUserNegativeTest@3bfdc050]" name="tearDown" is-config="true" duration-ms="1928" started-at="2019-02-08T10:55:16Z" finished-at="2019-02-08T10:55:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.elearning.functional.TC69AddUserNegativeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
